commerce_add_to_cart_link.settings:
  type: config_object
  label: 'Commerce Add To Cart Link settings'
  csrf_token:
    type: mapping
    label: 'Protect links with CSRF token'
    mapping:
      roles:
        type: sequence
        label: 'User roles to protect links with CSRF token'
  redirect_back:
    type: boolean
    label: 'Redirect back to referer'
